### ISSUE TITLE
Failed to open device: -3

### ISSUE THREAD

**Issue by JacobCZ** [dlech/fprint-demo#1]
I've tried compiling and running this on my ThinkPad T460 with Fedora 25. It compiled without errors or warnings, but when I try to launch it, I get this error.
```Failed to open device: -3```

The FP reader in my laptop is ```Validity VFS5011```

**Comment by dlech** [comment]
You can try setting the environment variable `LIBFPRINT_DEBUG=1`. I think higher numbers give more verbose output. There is also a similar environment variable for libusb to get more messages.

**Comment by JacobCZ** [comment]
Okay, so it seems that it needs to be launched with ```sudo```. Unfortunately, I haven't yet found a way to launch Gtk apps with sudo 😕 Any ideas?

**Comment by dlech** [comment]
`gksudo`

But really it would be better for you to set up a udev rule to make your fingerprint reader usable as non-root. Libfprint ships with udev rules, if you installed it from a package, I would think the correct rules should be installed already  (I don't use Fedora).

Here are the rules for Validity VFS5011 from my system

```
# Validity VFS5011
SUBSYSTEM=="usb", ATTRS{idVendor}=="138a", ATTRS{idProduct}=="0011", ATTRS{dev}=="*", TEST=="power/control", ATTR{power/control}="auto", MODE="0664", GROUP="plugdev"
SUBSYSTEM=="usb", ATTRS{idVendor}=="138a", ATTRS{idProduct}=="0017", ATTRS{dev}=="*", TEST=="power/control", ATTR{power/control}="auto", MODE="0664", GROUP="plugdev"
SUBSYSTEM=="usb", ATTRS{idVendor}=="138a", ATTRS{idProduct}=="0018", ATTRS{dev}=="*", TEST=="power/control", ATTR{power/control}="auto", MODE="0664", GROUP="plugdev"
```

If these rules are already installed, then it could be that you need to add yourself to the `plugdev` group.

**Comment by JacobCZ** [comment]
Okay, now it works! Thanks!
